### ISSUE TITLE
Unable to use Wevolor in home assistant

### ISSUE THREAD

**Issue by mwatz1234** [timstallmann/home-assistant-wevolor#1]
Had a working setup and I noticed this morning unable to use Wevolor with home assistant app.
I can use the Wevolor via web api without issues.

Not sure if home assistant did a update that is causing issues.
Fails with the last 2 docker releases 2023.5.0 & 2023.5.1

I tried to remove and add one of the groups, but the re-created group in home assistant doesn't show up.

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/wevolor/__init__.py:24 
Integration: Wevolor Control for Levolor Motorized Blinds 
First occurred: 9:26:20 AM (9 occurrences) 
Last logged: 9:31:12 AM

Error setting up entry Laundry for wevolor
Error setting up entry Bonus Room for wevolor
Error setting up entry All Blinds for wevolor
Error setting up entry All Blinds, but Bedrooms for wevolor
Error setting up entry Blinds for wevolor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/wevolor/__init__.py", line 24, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

When I try to add a group
```
2023-05-04 21:31:01.709 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Blinds for wevolor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/wevolor/__init__.py", line 24, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by mitch-b** [comment]
I have the same experience after upgrading my installation with May's changes - it seems like a breaking change might've been introduced on Home Assistant's side.

**Comment by xkadafix** [comment]
rolling back to ha core 2023.4.6 for the time being

**Comment by timstallmann** [comment]
Thx for flagging this! I'll take a look when I get a chance, may not be for a week or two.

**Comment by mitch-b** [comment]
This is due to https://github.com/home-assistant/core/pull/91929 .

Opening a PR ... and going to test the "simple" change.

**Comment by timstallmann** [comment]
Merged this! @mwatz1234 can you confirm if the update fixes things for you?

**Comment by mitch-b** [comment]
@timstallmann  do you need to trigger a new release for HACS to pick up the update?

**Comment by mwatz1234** [comment]
> @timstallmann  do you need to trigger a new release for HACS to pick up the update?

I would think so, HACs doesn't show an update available I had putty in my setup and make the update manually

**Comment by mitch-b** [comment]
Thanks for the release of 1.1.1, @timstallmann. I verified the HACS download of that version fixed my HA instance issues. This can be closed.
